package kr.co.farmerflood.trigger.provider.live;
import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*; import java.util.function.Function; import java.util.stream.Collectors;
import kr.co.farmerflood.trigger.config.AppProperties; import kr.co.farmerflood.trigger.domain.*; import kr.co.farmerflood.trigger.provider.*;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.stereotype.Component; import org.springframework.web.reactive.function.client.WebClient; import tools.jackson.databind.JsonNode;
@Component @ConditionalOnProperty(name="app.provider-mode",havingValue="live")
public class HrfcoStationCatalogue implements WaterStationCatalogue {
 private static final ZoneId KST=ZoneId.of("Asia/Seoul"); private static final DateTimeFormatter TIME=DateTimeFormatter.ofPattern("yyyyMMddHHmm"); private final AppProperties p; private final WebClient client; private volatile Cache cache;
 public HrfcoStationCatalogue(AppProperties p,WebClient.Builder b){this.p=p;client=b.baseUrl(p.getHrfco().getBaseUrl()).build();}
 public List<StationSummary> chungbukStations(){if(p.getHrfco().getApiKey().isBlank())throw new ProviderException("HRFCO","HRFCO_API_KEY is missing");Cache c=cache;if(c==null||c.loadedAt().isBefore(Instant.now().minus(Duration.ofMinutes(10)))){synchronized(this){c=cache;if(c==null||c.loadedAt().isBefore(Instant.now().minus(Duration.ofMinutes(10)))){try{cache=c=load();}catch(RuntimeException error){if(c==null)throw error;return c.stations();}}}}return c.stations();}
 private Cache load(){JsonNode info=get("/{key}/waterlevel/info.json");JsonNode latest=get("/{key}/waterlevel/list/10M.json");Map<String,JsonNode> readings=new HashMap<>();for(JsonNode n:latest.path("content")){readings.put(n.path("wlobscd").asText(),n);}List<StationSummary> result=new ArrayList<>();for(JsonNode n:info.path("content")){String addr=n.path("addr").asText().trim();if(!addr.startsWith("충청북도"))continue;double lat=dms(n.path("lat").asText()),lon=dms(n.path("lon").asText());if(!Double.isFinite(lat)||!Double.isFinite(lon))continue;var grid=KmaGridConverter.from(lat,lon);var thresholds=new WaterThresholds(number(n,"attwl"),number(n,"wrnwl"),number(n,"almwl"),number(n,"srswl"));JsonNode reading=readings.get(n.path("wlobscd").asText());Double level=reading==null?null:number(reading,"wl");Instant observed=reading==null?null:time(reading.path("ymdhm").asText());result.add(new StationSummary(n.path("wlobscd").asText(),n.path("obsnm").asText(),addr,lat,lon,grid.nx(),grid.ny(),level,observed,risk(level,thresholds),thresholds));}result.sort(Comparator.comparing(StationSummary::address).thenComparing(StationSummary::stationName));return new Cache(Instant.now(),List.copyOf(result));}
 private JsonNode get(String path){JsonNode body=client.get().uri(path,p.getHrfco().getApiKey()).retrieve().bodyToMono(JsonNode.class).block(Duration.ofSeconds(30));if(body==null||!body.path("content").isArray())throw new ProviderException("HRFCO",body==null?"empty response":"code="+body.path("code").asText());return body;}
 private String risk(Double l,WaterThresholds t){if(l==null)return "자료없음";if(!t.complete())return "기준없음";if(l>=t.serious())return "심각";if(l>=t.alert())return "경계";if(l>=t.caution())return "주의";if(l>=t.attention())return "관심";return "현재";}
 private Double number(JsonNode n,String key){String v=n.path(key).asText().trim();if(v.isEmpty())return null;try{return Double.valueOf(v);}catch(NumberFormatException e){return null;}}
 private double dms(String raw){try{String[] p=raw.trim().split("-");return Double.parseDouble(p[0])+Double.parseDouble(p[1])/60+Double.parseDouble(p[2])/3600;}catch(RuntimeException e){return Double.NaN;}}
 private Instant time(String raw){try{return LocalDateTime.parse(raw.replaceAll("[^0-9]","").substring(0,12),TIME).atZone(KST).toInstant();}catch(RuntimeException e){return null;}}
 private record Cache(Instant loadedAt,List<StationSummary> stations){}
}
