package kr.co.farmerflood.trigger.service;

import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;
import kr.co.farmerflood.trigger.persistence.*;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service
public class MobileAppService {
    private final FarmlandService farmlands;private final ChungbukRegionService regions;private final FarmMapService farmMap;private final AuthSessionJpaRepository sessions;private final MobileNotificationJpaRepository notifications;private final AppUserJpaRepository users;private final FarmlandJpaRepository farmlandEntities;private final FarmlandStationJpaRepository stationLinks;private final AlertJpaRepository alerts;private final TriggerStateJpaRepository triggerStates;
    public MobileAppService(FarmlandService f,ChungbukRegionService r,FarmMapService farmMap,AuthSessionJpaRepository s,MobileNotificationJpaRepository n,AppUserJpaRepository users,FarmlandJpaRepository farmlandEntities,FarmlandStationJpaRepository stationLinks,AlertJpaRepository alerts,TriggerStateJpaRepository triggerStates){farmlands=f;regions=r;this.farmMap=farmMap;sessions=s;notifications=n;this.users=users;this.farmlandEntities=farmlandEntities;this.stationLinks=stationLinks;this.alerts=alerts;this.triggerStates=triggerStates;}
    @Transactional public SessionView signup(String name,String phone,String district,String locality,String parcelId){regions.validate(district,locality);var parcel=farmMap.parcel(parcelId);if(!district.equals(parcel.district())||!locality.equals(parcel.locality()))throw new IllegalArgumentException("선택한 농경지가 행정구역과 일치하지 않습니다.");var user=farmlands.createMobileUser(name,phone);var farm=farmlands.register(new FarmlandService.RegisterFarmland(user.id(),parcel.cropType()+" 농경지",parcel.address(),parcel.province(),parcel.district(),parcel.locality(),parcel.id(),parcel.pnu(),parcel.areaSquareMeters(),parcel.latitude(),parcel.longitude(),parcel.geometryGeoJson(),"farmmap-"+parcel.id()));return session(user,farm);}
    @Transactional public SessionView login(String name,String phone){var user=farmlands.authenticate(name,phone).orElseThrow(()->new IllegalArgumentException("이름 또는 전화번호가 일치하지 않습니다."));var farms=farmlands.byUser(user.id());return session(user,farms.isEmpty()?null:farms.get(0));}
    @Transactional public SessionView guardianSignup(String guardianName,String farmerName,String farmerPhone){var guardian=farmlands.createGuardian(guardianName,farmerName,farmerPhone);return guardianSession(guardian);}
    @Transactional public SessionView guardianLogin(String guardianName,String farmerName,String farmerPhone){var guardian=farmlands.authenticateGuardian(guardianName,farmerName,farmerPhone).orElseThrow(()->new IllegalArgumentException("보호자 또는 농업인 정보가 일치하지 않습니다."));return guardianSession(guardian);}
    public SessionView me(String token){var s=require(token);var user=farmlands.user(s.userId);String targetId=targetUserId(user);var farms=farmlands.byUser(targetId);String targetName="GUARDIAN".equals(user.role())?farmlands.user(targetId).name():null;return new SessionView(token,user,farms.isEmpty()?null:farms.get(0),targetName);}
    public List<NotificationView> notifications(String token){var user=farmlands.user(require(token).userId);return notifications.findByUserIdOrderByCreatedAtDesc(targetUserId(user)).stream().map(this::view).toList();}
    @Transactional public void markRead(String token,String id){var user=farmlands.user(require(token).userId);if("GUARDIAN".equals(user.role()))throw new SecurityException("보호자 조회는 농업인의 확인 상태를 변경하지 않습니다.");var n=notifications.findById(id).orElseThrow();if(!n.userId.equals(user.id()))throw new SecurityException("알림 접근 권한이 없습니다.");n.readAt=Instant.now();notifications.save(n);}
    @Transactional public void withdraw(String token){var session=require(token);var current=farmlands.user(session.userId);String userId=current.id();if("GUARDIAN".equals(current.role())){sessions.deleteByUserId(userId);users.deleteById(userId);return;}for(var guardian:users.findByTargetFarmerId(userId)){sessions.deleteByUserId(guardian.id);users.deleteById(guardian.id);}for(var farm:farmlandEntities.findByUserIdOrderByCreatedAtDesc(userId)){stationLinks.deleteByFarmlandId(farm.id);triggerStates.deleteById(farm.id);}farmlandEntities.deleteAll(farmlandEntities.findByUserIdOrderByCreatedAtDesc(userId));notifications.deleteByUserId(userId);sessions.deleteByUserId(userId);for(var alert:alerts.findByUserId(userId)){alert.userId=null;alert.farmlandId=null;alert.locationName="탈퇴 사용자 농경지";alert.productionDecision="회원 탈퇴로 수신 대상 익명화";alerts.save(alert);}users.deleteById(userId);}
    @Transactional public void publishReady(kr.co.farmerflood.trigger.domain.AlertEvent alert,String mediaUrl){if(alert.userId()==null||!users.existsById(alert.userId())||notifications.existsByUserIdAndAlertId(alert.userId(),alert.id()))return;MobileNotificationEntity n=new MobileNotificationEntity();n.id=UUID.randomUUID().toString();n.userId=alert.userId();n.alertId=alert.id();n.title="침수 위험 경고 영상이 도착했습니다";n.body=alert.locationName()+" 인근 침수 위험을 확인하세요.";n.mediaUrl=mediaUrl;n.createdAt=Instant.now();notifications.save(n);}
    private SessionView session(FarmlandService.UserView user,FarmlandService.FarmlandView farm){AuthSessionEntity s=new AuthSessionEntity();s.token=UUID.randomUUID().toString();s.userId=user.id();s.createdAt=Instant.now();s.expiresAt=s.createdAt.plus(90,ChronoUnit.DAYS);sessions.save(s);return new SessionView(s.token,user,farm,null);}
    private SessionView guardianSession(FarmlandService.UserView guardian){String targetId=targetUserId(guardian);var farms=farmlands.byUser(targetId);AuthSessionEntity s=new AuthSessionEntity();s.token=UUID.randomUUID().toString();s.userId=guardian.id();s.createdAt=Instant.now();s.expiresAt=s.createdAt.plus(90,ChronoUnit.DAYS);sessions.save(s);return new SessionView(s.token,guardian,farms.isEmpty()?null:farms.get(0),farmlands.user(targetId).name());}
    private String targetUserId(FarmlandService.UserView user){if(!"GUARDIAN".equals(user.role()))return user.id();if(user.targetFarmerId()==null||!users.existsById(user.targetFarmerId()))throw new IllegalStateException("연결된 농업인 계정을 찾을 수 없습니다.");return user.targetFarmerId();}
    private AuthSessionEntity require(String token){var s=sessions.findById(token).orElseThrow(()->new SecurityException("로그인이 필요합니다."));if(s.expiresAt.isBefore(Instant.now()))throw new SecurityException("로그인이 만료되었습니다.");return s;}
    private NotificationView view(MobileNotificationEntity n){return new NotificationView(n.id,n.alertId,n.title,n.body,n.mediaUrl,n.createdAt,n.readAt);}
    public record SessionView(String token,FarmlandService.UserView user,FarmlandService.FarmlandView farmland,String targetFarmerName){}
    public record NotificationView(String id,String alertId,String title,String body,String mediaUrl,Instant createdAt,Instant readAt){}
}
