package kr.co.farmerflood.trigger.web;
import java.util.*; import kr.co.farmerflood.trigger.domain.*; import kr.co.farmerflood.trigger.provider.mock.MockScenarioStore; import kr.co.farmerflood.trigger.service.*;
import org.springframework.beans.factory.ObjectProvider; import org.springframework.core.io.FileSystemResource; import org.springframework.http.*; import org.springframework.http.codec.ServerSentEvent; import org.springframework.web.bind.annotation.*; import reactor.core.publisher.Flux;
@RestController @RequestMapping("/api") public class TriggerController {
 private final TriggerEngine engine;private final AlertRepository alerts;private final WebNotificationGateway notifications;private final ObjectProvider<MockScenarioStore> mocks;private final StationDashboardService dashboard;private final MockDemoStationService demoStations;private final VideoProductionJobRepository videoJobs;private final FloodVideoWorkflowClient workflowClient;
 public TriggerController(TriggerEngine e,AlertRepository a,WebNotificationGateway n,ObjectProvider<MockScenarioStore> m,StationDashboardService d,MockDemoStationService demos,VideoProductionJobRepository v,FloodVideoWorkflowClient w){engine=e;alerts=a;notifications=n;mocks=m;dashboard=d;demoStations=demos;videoJobs=v;workflowClient=w;}
 @GetMapping("/trigger/status")public Collection<TriggerState> status(){return engine.states();}@PostMapping("/trigger/evaluate")public Collection<TriggerState> evaluate(){return engine.evaluateAll();}@GetMapping("/alerts")public List<AlertEvent> alerts(){return alerts.findAll();}@GetMapping("/alerts/{id}")public AlertEvent alert(@PathVariable String id){return alerts.find(id);}
 @GetMapping(value="/notifications/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE)public Flux<ServerSentEvent<NotificationMessage>> stream(){return notifications.stream().map(n->ServerSentEvent.<NotificationMessage>builder(n).event("flood-alert").id(n.alertId()).build());}
 @PostMapping("/mock/scenario")public MockScenarioStore.State scenario(@RequestBody Scenario r){MockScenarioStore s=mocks.getIfAvailable();if(s==null)throw new IllegalStateException("Mock mode is not enabled");return s.update(r.waterLevelMeters(),r.riskLevel(),r.rainfallMm());}
 @GetMapping("/stations")public reactor.core.publisher.Mono<java.util.List<StationSummary>> stations(@RequestParam(required=false)String district,@RequestParam(defaultValue="false")boolean thresholdOnly){return reactor.core.publisher.Mono.fromCallable(()->dashboard.stations(district,thresholdOnly)).subscribeOn(reactor.core.scheduler.Schedulers.boundedElastic());}
 @GetMapping("/stations/{code}")public reactor.core.publisher.Mono<StationDetail> station(@PathVariable String code){return reactor.core.publisher.Mono.fromCallable(()->dashboard.detail(code)).subscribeOn(reactor.core.scheduler.Schedulers.boundedElastic());}
 @PostMapping("/stations/{code}/trigger")public StationDetail triggerMock(@PathVariable String code){return demoStations.trigger(code);}
 @PostMapping("/stations/{code}/normal-return")public StationDetail returnMock(@PathVariable String code){return demoStations.normalReturn(code);}
 @GetMapping("/production-jobs")public List<VideoProductionJob> productionJobs(){return videoJobs.findAll();}
 @GetMapping("/production-jobs/{id}")public VideoProductionJob productionJob(@PathVariable String id){VideoProductionJob j=videoJobs.find(id);if(j==null)throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND);return j;}
 @GetMapping("/production-jobs/{id}/detail")public reactor.core.publisher.Mono<Map<String,Object>> productionDetail(@PathVariable String id){VideoProductionJob j=requiredJob(id);if(j.getWorkerJobId()==null)return reactor.core.publisher.Mono.just(detailResponse(j,Map.of("status","QUEUED","message","Worker 작업 요청 대기")));return workflowClient.detail(j.getWorkerJobId()).map(worker->detailResponse(j,worker));}
 @GetMapping("/production-jobs/{id}/logs")public reactor.core.publisher.Mono<Map<String,Object>> productionLogs(@PathVariable String id,@RequestParam(defaultValue="workflow")String source,@RequestParam(defaultValue="0")long after){VideoProductionJob j=requiredJob(id);if(j.getWorkerJobId()==null)return reactor.core.publisher.Mono.just(Map.of("source",source,"after",after,"next",after,"text","","available",false));return workflowClient.logs(j.getWorkerJobId(),source,after);}
 @GetMapping("/production-jobs/{id}/video")public ResponseEntity<FileSystemResource> productionVideo(@PathVariable String id)throws java.io.IOException{VideoProductionJob j=videoJobs.find(id);if(j==null||j.getFinalVideoPath()==null)throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND);var resource=new FileSystemResource(j.getFinalVideoPath());return ResponseEntity.ok().contentType(MediaType.valueOf("video/mp4")).contentLength(resource.contentLength()).body(resource);}
 private VideoProductionJob requiredJob(String id){VideoProductionJob j=videoJobs.find(id);if(j==null)throw new org.springframework.web.server.ResponseStatusException(HttpStatus.NOT_FOUND);return j;}
 private Map<String,Object> detailResponse(VideoProductionJob job,Map<String,Object> worker){Map<String,Object> result=new LinkedHashMap<>();result.put("productionJob",job);result.put("worker",worker);return result;}
 public record Scenario(double waterLevelMeters,RiskLevel riskLevel,double rainfallMm){}
}
