package kr.co.farmerflood.mobile;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.ActivityInfo;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.view.*;import android.webkit.*;import android.widget.*;import org.json.*;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity {
    private enum Screen {WELCOME, ROLE, IDENTITY, LOCATION, FARM_MAP, HOME, VIDEO}
    private LinearLayout root;private EditText name,phone;private Spinner district,locality;private JSONObject regionData;private String pendingName,pendingPhone,selectedDistrict,selectedLocality;private boolean videoMode,farmMapMode,lastLogin,guardianFlow;private Screen screen=Screen.WELCOME;private final Handler guardianHandler=new Handler(Looper.getMainLooper());private Runnable guardianPoll;private TextView guardianStatusView;private final BroadcastReceiver newAlertReceiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(screen==Screen.HOME&&guardianStatusView!=null)startGuardianStatus(guardianStatusView);}};
    @Override public void onCreate(Bundle b){super.onCreate(b);IntentFilter filter=new IntentFilter("kr.co.farmerflood.mobile.NEW_ALERT");if(Build.VERSION.SDK_INT>=33)registerReceiver(newAlertReceiver,filter,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(newAlertReceiver,filter);if(Build.VERSION.SDK_INT>=33){getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::handleBack);if(checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},100);}String video=getIntent().getStringExtra("mediaUrl");if(video!=null){showVideo(video);return;}String token=prefs().getString("token",null);if(token==null||token.isBlank())showWelcome();else showHome();}
    @Override protected void onDestroy(){stopGuardianPoll();try{unregisterReceiver(newAlertReceiver);}catch(Exception ignored){}super.onDestroy();}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);String video=i.getStringExtra("mediaUrl");if(video!=null)showVideo(video);}
    @Override public void onBackPressed(){handleBack();}
    private void handleBack(){if(screen==Screen.VIDEO){exitVideo();return;}if(screen==Screen.FARM_MAP){showLocation();return;}if(screen==Screen.ROLE||screen==Screen.IDENTITY||screen==Screen.LOCATION){pendingName=null;pendingPhone=null;showWelcome();return;}if(screen==Screen.HOME){moveTaskToBack(true);return;}finish();}
    private boolean easy(){return prefs().getBoolean("easyMode",false);}
    private void base(){stopGuardianPoll();videoMode=false;farmMapMode=false;setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_VERTICAL);root.setPadding(dp(easy()?14:24),dp(easy()?16:32),dp(easy()?14:24),dp(easy()?24:32));GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(235,247,240),Color.rgb(248,246,235),Color.rgb(239,245,250)});root.setBackground(bg);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(root,new ScrollView.LayoutParams(-1,-1));FrameLayout frame=new FrameLayout(this);frame.setPadding(0,statusBarInset()+dp(8),0,0);frame.setBackgroundColor(Color.rgb(235,247,240));FrameLayout.LayoutParams scrollParams=new FrameLayout.LayoutParams(-1,-1);scrollParams.bottomMargin=dp(easy()?94:62);frame.addView(scroll,scrollParams);addModeButton(frame);setContentView(frame);scroll.post(this::showSystemBars);}
    private void addModeButton(FrameLayout frame){Button mode=new Button(this);mode.setText(easy()?"자세한 모드":"쉬운 모드");mode.setAllCaps(false);mode.setTextSize(easy()?24:16);mode.setTypeface(null,1);mode.setTextColor(Color.WHITE);mode.setPadding(dp(8),0,dp(8),0);mode.setMinHeight(0);mode.setMinimumHeight(0);mode.setBackground(round(Color.rgb(74,82,78),14,Color.TRANSPARENT));mode.setElevation(dp(8));mode.setOnClickListener(v->{prefs().edit().putBoolean("easyMode",!easy()).apply();redrawCurrent();});FrameLayout.LayoutParams p=new FrameLayout.LayoutParams(dp(easy()?166:112),dp(easy()?68:44),Gravity.START|Gravity.BOTTOM);p.setMargins(dp(14),dp(10),0,dp(14));frame.addView(mode,p);}
    private void redrawCurrent(){switch(screen){case WELCOME->showWelcome();case ROLE->showRoleChoice(lastLogin);case IDENTITY->{if(guardianFlow)showGuardianAuth(lastLogin);else showIdentity(lastLogin);}case LOCATION->showLocation();case FARM_MAP->showFarmMap();case HOME->showHome();default->{}}}
    private int statusBarInset(){int id=getResources().getIdentifier("status_bar_height","dimen","android");return id>0?getResources().getDimensionPixelSize(id):dp(28);}
    private void easyTitleGap(){if(!easy())return;Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,dp(24)));}
    private void easyObjectGap(){if(!easy())return;Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,dp(36)));}
    private TextView text(String value,int size,boolean bold){TextView v=new TextView(this);v.setText(value);v.setTextSize(easy()?Math.max(34,size+12):size);if(easy())v.setAutoSizeTextTypeUniformWithConfiguration(30,50,2,android.util.TypedValue.COMPLEX_UNIT_SP);v.setTextColor(Color.rgb(24,49,39));if(bold)v.setTypeface(null,1);v.setPadding(0,dp(easy()?10:6),0,dp(easy()?16:8));root.addView(v);return v;}
    private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(easy()?34:17);e.setSingleLine(true);e.setPadding(dp(easy()?22:18),0,dp(easy()?22:18),0);e.setBackground(round(Color.WHITE,16,Color.rgb(215,227,220)));e.setElevation(dp(1));root.addView(e,new LinearLayout.LayoutParams(-1,dp(easy()?104:60)));space();return e;}
    private Button button(String label){Button b=new Button(this);b.setText(label);b.setTextColor(Color.WHITE);b.setTextSize(easy()?44:16);if(easy())b.setAutoSizeTextTypeUniformWithConfiguration(32,48,2,android.util.TypedValue.COMPLEX_UNIT_SP);b.setTypeface(null,easy()?1:0);b.setAllCaps(false);b.setSingleLine(true);b.setPadding(dp(12),dp(2),dp(12),dp(2));b.setMinHeight(0);b.setMinimumHeight(0);b.setBackground(round(Color.rgb(23,107,67),18,Color.TRANSPARENT));b.setElevation(dp(3));root.addView(b,new LinearLayout.LayoutParams(-1,dp(easy()?108:56)));space();return b;}
    private TextView badge(String value,int fg,int bg){TextView v=new TextView(this);v.setText(value);v.setTextColor(fg);v.setTextSize(13);v.setTypeface(null,1);v.setGravity(Gravity.CENTER);v.setPadding(dp(12),dp(8),dp(12),dp(8));v.setBackground(round(bg,20,Color.TRANSPARENT));return v;}
    private LinearLayout infoRow(String label,String value,int tint){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(easy()?18:16),dp(easy()?14:12),dp(easy()?18:16),dp(easy()?14:12));TextView l=new TextView(this);l.setText(label);l.setTextSize(easy()?29:12);l.setTypeface(null,1);l.setTextColor(tint);TextView v=new TextView(this);v.setText(value);v.setTextSize(easy()?36:16);v.setTypeface(null,1);v.setTextColor(Color.rgb(25,46,40));v.setPadding(0,dp(easy()?7:3),0,0);v.setBreakStrategy(android.text.Layout.BREAK_STRATEGY_HIGH_QUALITY);row.addView(l);row.addView(v);return row;}
    private GradientDrawable round(int color,int radius,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private void space(){Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,dp(easy()?24:12)));}
    private void showWelcome(){screen=Screen.WELCOME;base();if(!easy()){TextView mark=text("FARM SAFE · CHUNGBUK",13,true);mark.setTextColor(Color.rgb(24,115,79));}text(easy()?"홍수 경고":"우리 가족을 위한\n한발 빠른 홍수 경고",34,true);if(!easy()){TextView intro=text("농업인과 보호자가 함께 농경지 주변의\n위험을 확인하고 경고 영상을 받아보세요.",16,false);intro.setTextColor(Color.rgb(71,91,83));LinearLayout features=new LinearLayout(this);features.setOrientation(LinearLayout.HORIZONTAL);features.setGravity(Gravity.CENTER);features.setPadding(0,dp(12),0,dp(20));features.addView(badge("실시간 수위",Color.rgb(18,96,69),Color.rgb(218,241,230)));features.addView(badge("24시간 강우",Color.rgb(37,91,145),Color.rgb(222,237,250)));features.addView(badge("가족 공유",Color.rgb(140,82,18),Color.rgb(250,234,207)));root.addView(features);}easyTitleGap();Button signup=button(easy()?"가입":"처음 가입하기");easyObjectGap();Button login=button(easy()?"로그인":"기존 회원 로그인");login.setTextColor(Color.rgb(23,107,67));login.setBackground(round(Color.argb(235,255,255,255),16,Color.rgb(174,207,190)));signup.setOnClickListener(v->showRoleChoice(false));login.setOnClickListener(v->showRoleChoice(true));}
    private void showRoleChoice(boolean login){screen=Screen.ROLE;lastLogin=login;base();if(!easy())text(login?"로그인 유형":"가입 유형",13,true).setTextColor(Color.rgb(23,107,67));text(easy()?"나는 누구인가요?":"어떤 역할로\n이용하시나요?",30,true);if(!easy())text("본인에게 맞는 유형을 선택해주세요.",16,false);easyTitleGap();Button farmer=button("농업인 "+(login?"로그인":"가입"));easyObjectGap();Button guardian=button("보호자 "+(login?"로그인":"가입"));guardian.setTextColor(Color.rgb(38,91,145));guardian.setBackground(round(Color.rgb(229,240,250),16,Color.rgb(174,203,226)));farmer.setOnClickListener(v->showIdentity(login));guardian.setOnClickListener(v->showGuardianAuth(login));}
    private void showGuardianAuth(boolean login){screen=Screen.IDENTITY;lastLogin=login;guardianFlow=true;base();if(!easy())text(login?"보호자 로그인":"보호자 가입",13,true).setTextColor(Color.rgb(38,91,145));text(easy()?"정보 입력":"보호자와 농업인\n정보를 입력하세요",29,true);if(!easy())text("연결할 농업인은 먼저 농업인 가입이 완료되어 있어야 합니다.",15,false);EditText guardianName=input("보호자 이름");EditText farmerName=input("농업인 이름");EditText farmerPhone=input("농업인 전화번호");farmerPhone.setInputType(3);Button submit=button(login?"로그인":"가입 완료");submit.setBackground(round(Color.rgb(38,101,151),16,Color.TRANSPARENT));submit.setOnClickListener(v->{String g=guardianName.getText().toString().trim(),f=farmerName.getText().toString().trim(),p=farmerPhone.getText().toString().trim();if(g.isEmpty()||f.isEmpty()||p.length()<10){toast("보호자와 농업인 정보를 확인해주세요.");return;}JSONObject body=new JSONObject();try{body.put("guardianName",g).put("farmerName",f).put("farmerPhone",p);}catch(Exception ignored){}authenticateGuardian(login?"/api/mobile/auth/guardian/login":"/api/mobile/auth/guardian/signup",body,g);});}
    private void showIdentity(boolean login){screen=Screen.IDENTITY;lastLogin=login;guardianFlow=false;base();if(!easy()){TextView step=text(login?"다시 만나 반가워요":"회원가입 · 1/3",13,true);step.setTextColor(Color.rgb(23,107,67));}text(login?(easy()?"로그인":"기존 회원 로그인"):(easy()?"정보 입력":"기본 정보를\n알려주세요"),30,true);if(!easy())text(login?"가입할 때 사용한 정보를 입력해주세요.":"재난 알림을 정확히 전달하는 데 사용합니다.",16,false);name=input("이름");phone=input(easy()?"전화번호":"전화번호 (예: 01012345678)");phone.setInputType(3);Button next=button(login?"확인":"농경지 등록");next.setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()||phone.getText().toString().trim().length()<10){toast("이름과 전화번호를 확인해주세요.");return;}if(login)authenticate("/api/mobile/auth/login",null);else{pendingName=name.getText().toString().trim();pendingPhone=phone.getText().toString().trim();showLocation();}});}
    private void showLocation(){screen=Screen.LOCATION;base();if(!easy())text("농경지 등록 · 2/3",13,true).setTextColor(Color.rgb(38,102,151));text(easy()?"농경지 지역":"농경지가 있는\n지역을 선택하세요",28,true);if(!easy())text("선택한 지역의 공식 팜맵으로 이동합니다.",15,false);text("도/광역시",13,true);Spinner province=new Spinner(this);styleSpinner(province);province.setAdapter(spinnerAdapter(List.of("충청북도")));root.addView(province,new LinearLayout.LayoutParams(-1,dp(easy()?96:56)));space();text("시/군",13,true);district=new Spinner(this);styleSpinner(district);root.addView(district,new LinearLayout.LayoutParams(-1,dp(easy()?96:56)));space();text("읍/면/동",13,true);locality=new Spinner(this);styleSpinner(locality);root.addView(locality,new LinearLayout.LayoutParams(-1,dp(easy()?96:56)));space();Button submit=button(easy()?"지도 보기":"지도에서 내 농경지 찾기  →");submit.setEnabled(false);submit.setOnClickListener(v->showFarmMap());new Thread(()->{try{regionData=Api.get("/api/mobile/regions",null).getJSONObject("districts");List<String> districts=new ArrayList<>();regionData.keys().forEachRemaining(districts::add);runOnUiThread(()->{district.setAdapter(spinnerAdapter(districts));district.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){loadLocalities(districts.get(pos));}});submit.setEnabled(true);});}catch(Exception e){runOnUiThread(()->toast("행정구역을 불러오지 못했습니다: "+e.getMessage()));}}).start();}
    private void styleSpinner(Spinner spinner){spinner.setPadding(dp(12),0,dp(12),0);spinner.setBackground(round(Color.WHITE,14,Color.rgb(205,222,213)));}
    private ArrayAdapter<String> spinnerAdapter(List<String> values){return new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,values){private TextView item(int p,boolean dropdown){TextView t=new TextView(MainActivity.this);t.setText(getItem(p));t.setTextSize(easy()?32:16);t.setTextColor(Color.rgb(20,45,36));t.setBackgroundColor(Color.WHITE);t.setTypeface(null,easy()?1:0);t.setGravity(Gravity.CENTER_VERTICAL);t.setSingleLine(true);t.setPadding(dp(20),0,dp(20),0);if(dropdown)t.setLayoutParams(new android.widget.AbsListView.LayoutParams(-1,dp(easy()?84:56)));return t;}@Override public View getView(int p,View v,android.view.ViewGroup parent){return item(p,false);}@Override public View getDropDownView(int p,View v,android.view.ViewGroup parent){return item(p,true);}};}
    private void loadLocalities(String d){try{JSONArray a=regionData.getJSONArray(d);List<String> values=new ArrayList<>();for(int i=0;i<a.length();i++)values.add(a.getString(i));locality.setAdapter(spinnerAdapter(values));}catch(Exception e){toast(e.getMessage());}}
    private void showFarmMap(){if(district!=null&&district.getSelectedItem()!=null&&locality!=null&&locality.getSelectedItem()!=null){selectedDistrict=district.getSelectedItem().toString();selectedLocality=locality.getSelectedItem().toString();}if(selectedDistrict==null||selectedLocality==null)return;screen=Screen.FARM_MAP;farmMapMode=true;LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(0,statusBarInset()+dp(8),0,0);page.setBackgroundColor(Color.WHITE);Button back=new Button(this);back.setText(easy()?"← 지역 선택":"←  지역 다시 선택");back.setTextColor(Color.rgb(23,107,67));back.setTextSize(easy()?30:15);back.setTypeface(null,easy()?1:0);back.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);back.setPadding(dp(18),0,dp(18),0);back.setBackgroundColor(Color.WHITE);back.setOnClickListener(v->showLocation());page.addView(back,new LinearLayout.LayoutParams(-1,dp(easy()?88:54)));WebView web=new WebView(this);web.setBackgroundColor(Color.rgb(233,241,236));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);if(easy())web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView view,String url){applyEasyMap(view);}});web.addJavascriptInterface(new Object(){private void submit(JSONArray ids){runOnUiThread(()->{toast("선택한 농경지를 등록하고 있습니다.");signup(ids);});}@JavascriptInterface public void onParcelsSelected(String json){try{submit(new JSONArray(json));}catch(Exception e){runOnUiThread(()->toast("농경지 선택 정보를 확인할 수 없습니다."));}}@JavascriptInterface public void onParcelSelected(String json){try{JSONArray ids=new JSONArray();ids.put(new JSONObject(json).getString("id"));submit(ids);}catch(Exception e){runOnUiThread(()->toast("농경지 선택 정보를 확인할 수 없습니다."));}}},"AndroidFarmMap");page.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(page);showSystemBars();String url=BuildConfig.API_BASE_URL+"/mobile/farm-map?district="+URLEncoder.encode(selectedDistrict,StandardCharsets.UTF_8)+"&locality="+URLEncoder.encode(selectedLocality,StandardCharsets.UTF_8);web.loadUrl(url);}
    private void applyEasyMap(WebView web){web.evaluateJavascript("""
      (()=>{const guide=document.querySelector('.guide'),button=document.getElementById('completeButton');if(guide)guide.textContent='누르면 선택, 다시 누르면 해제';const css=document.createElement('style');css.textContent='.guide{font-size:24px;line-height:1.3;padding:18px 20px}.list-button{font-size:22px;padding:16px 20px;top:96px}.sheet{padding:18px}.sheet #title,.sheet .meta{display:none}.confirm{font-size:30px;min-height:76px;padding:12px}.leaflet-bottom.leaflet-right{right:auto;left:16px;bottom:160px}.leaflet-control-zoom a{width:58px!important;height:58px!important;line-height:58px!important;font-size:36px!important}.modal{padding:108px 14px 18px}.list-panel{padding:22px}.list-head{font-size:30px}.close{font-size:26px;padding:14px 18px}.parcel-row{padding:20px 2px}.parcel-copy b{font-size:30px}.remove{font-size:25px;padding:14px 16px}.list-empty{font-size:25px}';document.head.appendChild(css);window.renderList=()=>{const box=document.getElementById('parcelList'),items=[...selected.values()];box.innerHTML=items.length?items.map(f=>`<div class="parcel-row"><div class="parcel-copy"><b>${esc(f.properties.crop_type)} · ${Math.round(f.properties.area_sqm||0).toLocaleString()}㎡</b></div><button class="remove" onclick="removeParcel('${f.properties.id}')">삭제</button></div>`).join(''):'<div class="list-empty">선택한 농경지가 없습니다</div>'};const simplify=()=>{if(!button)return;const m=button.textContent.match(/(\\d+)개/);if(m&&button.textContent!==m[1]+'개 등록')button.textContent=m[1]+'개 등록'};simplify();if(button)new MutationObserver(simplify).observe(button,{childList:true,characterData:true,subtree:true});})()
      """,null);}
    private void signup(JSONArray parcelIds){JSONObject extra=new JSONObject();try{extra.put("district",selectedDistrict).put("locality",selectedLocality).put("parcelIds",parcelIds);}catch(Exception ignored){}authenticate("/api/mobile/auth/signup",extra);}
    private void authenticate(String path,JSONObject extra){boolean signup=path.endsWith("/signup");final String n=signup&&pendingName!=null?pendingName:name.getText().toString().trim(),p=signup&&pendingPhone!=null?pendingPhone:phone.getText().toString().trim();new Thread(()->{try{JSONObject body=extra==null?new JSONObject():extra;body.put("name",n).put("phone",p);JSONObject result=Api.post(path,body,null);saveSession(result,n);pendingName=null;pendingPhone=null;if(signup)prefs().edit().putBoolean("easyMode",true).commit();runOnUiThread(this::showHome);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}).start();}
    private void authenticateGuardian(String path,JSONObject body,String guardianName){new Thread(()->{try{JSONObject result=Api.post(path,body,null);saveSession(result,guardianName);runOnUiThread(this::showHome);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}).start();}
    private void saveSession(JSONObject result,String displayName)throws Exception{JSONObject user=result.optJSONObject("user");String role=user==null?"FARMER":user.optString("role","FARMER");prefs().edit().putString("token",result.getString("token")).putString("name",displayName).putString("role",role).putString("targetFarmerName",result.optString("targetFarmerName","")).remove("lastNotificationId").remove("notificationBaselineInitialized").commit();}
    private void showHome(){screen=Screen.HOME;base();startRelay();
        boolean guardian="GUARDIAN".equals(prefs().getString("role","FARMER"));String target=prefs().getString("targetFarmerName","농업인"),display=prefs().getString("name",guardian?"보호자":"농업인");LinearLayout header=new LinearLayout(this);header.setOrientation(LinearLayout.VERTICAL);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(easy()?22:18),dp(easy()?18:18),dp(easy()?22:18),dp(easy()?18:18));header.setMinimumHeight(dp(easy()?100:0));header.setBackground(round(guardian?Color.rgb(42,91,139):Color.rgb(26,105,77),22,Color.TRANSPARENT));header.setElevation(dp(3));TextView greeting=new TextView(this);greeting.setText(easy()?(guardian?display+" 보호자님":display+"님 농경지"):(guardian?display+"님은 보호자 로그인입니다.":display+"님, 안녕하세요"));greeting.setTextSize(easy()?42:(guardian?22:27));if(easy())greeting.setAutoSizeTextTypeUniformWithConfiguration(34,46,2,android.util.TypedValue.COMPLEX_UNIT_SP);greeting.setTypeface(null,1);greeting.setTextColor(Color.WHITE);header.addView(greeting);if(!easy()){TextView message=new TextView(this);message.setText(guardian?target+"님의 농경지 경고 영상 및\n조회 여부를 확인합니다.":"오늘도 농경지 주변의 하천과 비 소식을\n꼼꼼하게 살피고 있어요.");message.setTextSize(15);message.setTextColor(guardian?Color.rgb(221,237,250):Color.rgb(218,241,231));message.setPadding(0,dp(8),0,dp(12));header.addView(message);header.addView(badge(guardian?"●  보호자 안전 연결 중":"●  실시간 안전 감시 중",guardian?Color.rgb(37,82,125):Color.rgb(18,91,67),guardian?Color.rgb(225,239,251):Color.rgb(220,244,231)));}root.addView(header,new LinearLayout.LayoutParams(-1,-2));space();
        if(!easy()){TextView section=text(guardian?"대상 농경지":"내 농경지",18,true);section.setTextColor(Color.rgb(28,65,53));}LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(easy()?8:4),dp(easy()?10:6),dp(easy()?8:4),dp(easy()?10:6));card.setBackground(round(Color.argb(242,255,255,255),20,Color.rgb(218,229,222)));card.setElevation(dp(2));card.addView(infoRow("농경지",easy()?"불러오는 중":"정보를 불러오는 중입니다…",Color.rgb(29,112,79)));root.addView(card,new LinearLayout.LayoutParams(-1,-2));space();
        if(guardian){TextView readStatus=new TextView(this);readStatus.setText(easy()?"영상 확인 중":"최근 영상 확인 여부를 조회 중입니다…");readStatus.setTextSize(easy()?26:15);readStatus.setTypeface(null,1);readStatus.setTextColor(Color.rgb(151,43,43));readStatus.setGravity(Gravity.CENTER);readStatus.setPadding(dp(12),dp(easy()?7:15),dp(12),dp(easy()?7:15));readStatus.setMinHeight(dp(easy()?54:0));readStatus.setBackground(round(Color.rgb(251,231,231),16,Color.rgb(239,190,190)));root.addView(readStatus,new LinearLayout.LayoutParams(-1,-2));space();guardianStatusView=readStatus;startGuardianStatus(readStatus);}else{guardianStatusView=null;if(!easy()){LinearLayout notice=new LinearLayout(this);notice.setOrientation(LinearLayout.VERTICAL);notice.setPadding(dp(18),dp(16),dp(18),dp(16));notice.setBackground(round(Color.rgb(231,241,250),18,Color.TRANSPARENT));TextView noticeTitle=new TextView(this);noticeTitle.setText("최근 경고 영상");noticeTitle.setTextSize(15);noticeTitle.setTypeface(null,1);noticeTitle.setTextColor(Color.rgb(38,86,128));TextView noticeBody=new TextView(this);noticeBody.setText("가장 최근에 제작된 홍수 경고 영상을 다시 볼 수 있습니다.");noticeBody.setTextSize(14);noticeBody.setTextColor(Color.rgb(65,82,96));noticeBody.setPadding(0,dp(5),0,0);notice.addView(noticeTitle);notice.addView(noticeBody);root.addView(notice);space();}}Button refresh=button(easy()?"영상 보기":"경고 영상 재확인");if(easy()&&guardian)refresh.setLayoutParams(new LinearLayout.LayoutParams(-1,dp(94)));refresh.setBackground(round(Color.rgb(37,101,151),16,Color.TRANSPARENT));refresh.setOnClickListener(v->loadLatest());
        Space separation=new Space(this);root.addView(separation,new LinearLayout.LayoutParams(1,dp(easy()?14:28)));LinearLayout accountActions=new LinearLayout(this);accountActions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);Button logout=new Button(this);logout.setText("로그아웃");logout.setAllCaps(false);logout.setTextSize(easy()?25:14);logout.setTypeface(null,easy()?1:0);logout.setTextColor(Color.rgb(71,85,80));logout.setPadding(dp(3),0,dp(3),0);logout.setBackground(round(Color.argb(220,255,255,255),14,Color.rgb(205,216,210)));LinearLayout.LayoutParams logoutParams=new LinearLayout.LayoutParams(dp(easy()?140:138),dp(easy()?60:48));logoutParams.setMargins(0,0,dp(8),0);accountActions.addView(logout,logoutParams);Button withdraw=new Button(this);withdraw.setText("회원 탈퇴");withdraw.setAllCaps(false);withdraw.setTextSize(easy()?22:12);withdraw.setTypeface(null,easy()?1:0);withdraw.setPadding(dp(2),0,dp(2),0);withdraw.setTextColor(Color.rgb(169,54,54));withdraw.setBackground(round(Color.rgb(250,238,238),14,Color.TRANSPARENT));accountActions.addView(withdraw,new LinearLayout.LayoutParams(dp(easy()?124:112),dp(easy()?58:44)));root.addView(accountActions);logout.setOnClickListener(v->{boolean mode=easy();prefs().edit().clear().putBoolean("easyMode",mode).commit();pendingName=null;pendingPhone=null;stopService(new Intent(this,NotificationRelayService.class));showWelcome();});withdraw.setOnClickListener(v->confirmWithdrawal());
        new Thread(()->{try{JSONObject me=Api.get("/api/mobile/me",token());JSONObject f=me.optJSONObject("farmland");JSONArray types=me.optJSONArray("farmlandTypes");int count=me.optInt("farmlandCount",f==null?0:1);List<String> labels=new ArrayList<>();if(types!=null)for(int i=0;i<types.length();i++)labels.add(types.optString(i));runOnUiThread(()->{card.removeAllViews();if(f==null){card.addView(infoRow("농경지",easy()?"없음":"등록된 농경지가 없습니다.",Color.rgb(29,112,79)));return;}card.addView(infoRow("농경지 종류",labels.isEmpty()?f.optString("name","내 농경지"):String.join(" · ",labels),Color.rgb(29,112,79)));if(!easy())card.addView(infoRow("선택 필지",count+"개",Color.rgb(29,112,79)));String address=f.optString("address","위치 정보 없음");card.addView(infoRow("위치",easy()?easyAddress(address,f.optString("district","")):address,Color.rgb(38,101,151)));if(!easy())card.addView(infoRow("현재 상태","인근 하천 안전 감시 중",Color.rgb(151,91,28)));});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}).start();}
    private String easyAddress(String address,String districtName){if(address==null||address.isBlank()||districtName==null||districtName.isBlank())return address;String marker=districtName+" ";int at=address.indexOf(marker);return at<0?address:address.substring(0,at+districtName.length())+"\n"+address.substring(at+marker.length());}
    private void loadLatest(){new Thread(()->{try{JSONArray list=Api.getArray("/api/mobile/notifications",token());if(list.length()==0){runOnUiThread(()->toast("현재는 홍수 위험이 발생하지 않았습니다."));return;}JSONObject latest=list.getJSONObject(0);String url=latest.optString("mediaUrl","");if(url.isBlank()){runOnUiThread(()->toast("현재는 홍수 위험이 발생하지 않았습니다."));return;}runOnUiThread(()->showVideo(url,latest.optString("id",null)));}catch(Exception e){runOnUiThread(()->toast("현재는 홍수 위험이 발생하지 않았습니다."));}}).start();}
    private void startGuardianStatus(TextView view){stopGuardianPoll();guardianPoll=new Runnable(){@Override public void run(){if(screen!=Screen.HOME||view!=guardianStatusView)return;new Thread(()->{try{JSONArray list=Api.getArray("/api/mobile/notifications",token());if(list.length()==0){runOnUiThread(()->{if(view!=guardianStatusView)return;view.setText(easy()?"경고 영상 없음":"현재 확인할 경고 영상이 없습니다.");view.setTextColor(Color.rgb(108,91,64));view.setBackground(round(Color.rgb(248,240,219),16,Color.rgb(232,214,170)));guardianHandler.postDelayed(this,5000);});return;}JSONObject latest=list.getJSONObject(0);boolean read=!latest.isNull("readAt")&&!latest.optString("readAt","").isBlank();runOnUiThread(()->{if(view!=guardianStatusView)return;if(read){view.setText(easy()?"영상 확인 완료":"농업인이 최신 경고 영상을 확인했습니다.");view.setTextColor(Color.rgb(35,83,130));view.setBackground(round(Color.rgb(225,239,251),16,Color.rgb(169,204,231)));stopGuardianPoll();}else{view.setText(easy()?"영상 확인 전":"농업인이 아직 최신 경고 영상을 확인하지 않았습니다.");view.setTextColor(Color.rgb(151,43,43));view.setBackground(round(Color.rgb(251,231,231),16,Color.rgb(239,190,190)));guardianHandler.postDelayed(this,5000);}});}catch(Exception e){runOnUiThread(()->{if(view==guardianStatusView)guardianHandler.postDelayed(this,5000);});}}).start();}};guardianHandler.post(guardianPoll);}
    private void stopGuardianPoll(){if(guardianPoll!=null)guardianHandler.removeCallbacks(guardianPoll);guardianPoll=null;}
    private void showVideo(String path){showVideo(path,getIntent().getStringExtra("notificationId"));}
    private void showVideo(String path,String notificationId){
        screen=Screen.VIDEO;videoMode=true;
        if(notificationId!=null&&!"GUARDIAN".equals(prefs().getString("role","FARMER")))new Thread(()->{try{Api.post("/api/mobile/notifications/"+notificationId+"/read",null,token());}catch(Exception ignored){}}).start();
        // 가로 전환으로 Activity가 재생성되어도 홈 버튼/알림에서 받은 영상 주소를 유지한다.
        getIntent().putExtra("mediaUrl",path);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);
        FrameLayout stage=new FrameLayout(this);stage.setBackgroundColor(Color.BLACK);
        VideoView video=new VideoView(this);FrameLayout.LayoutParams videoParams=new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER);stage.addView(video,videoParams);
        Button close=new Button(this);close.setText("끄기  ✕");close.setAllCaps(false);close.setTextColor(Color.WHITE);close.setTextSize(24);close.setTypeface(null,1);close.setPadding(dp(12),0,dp(12),0);close.setBackground(round(Color.rgb(190,45,45),18,Color.TRANSPARENT));close.setElevation(dp(12));close.setOnClickListener(v->exitVideo());
        FrameLayout.LayoutParams closeParams=new FrameLayout.LayoutParams(dp(136),dp(64),Gravity.END|Gravity.TOP);
        closeParams.setMargins(dp(16),dp(16),dp(20),dp(16));stage.addView(close,closeParams);close.bringToFront();
        setContentView(stage);stage.post(this::hideSystemBars);video.setVideoURI(Uri.parse(BuildConfig.API_BASE_URL+path));MediaController controls=new MediaController(this){@Override public boolean dispatchKeyEvent(KeyEvent event){if(event.getKeyCode()==KeyEvent.KEYCODE_BACK){if(event.getAction()==KeyEvent.ACTION_UP)exitVideo();return true;}return super.dispatchKeyEvent(event);}};controls.setAnchorView(video);video.setMediaController(controls);video.setOnPreparedListener(mp->{mp.setLooping(false);int vw=mp.getVideoWidth(),vh=mp.getVideoHeight(),sw=stage.getWidth(),sh=stage.getHeight();if(vw>0&&vh>0&&sw>0&&sh>0){float scale=Math.min((float)sw/vw,(float)sh/vh);FrameLayout.LayoutParams centered=new FrameLayout.LayoutParams(Math.round(vw*scale),Math.round(vh*scale),Gravity.CENTER);video.setLayoutParams(centered);}video.start();close.bringToFront();});video.setOnErrorListener((mp,what,extra)->{toast("영상을 재생할 수 없습니다.");return true;});
    }
    private void exitVideo(){videoMode=false;getIntent().removeExtra("mediaUrl");getIntent().removeExtra("notificationId");showSystemBars();setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);showHome();}
    private void confirmWithdrawal(){AlertDialog dialog=new AlertDialog.Builder(this).setTitle("회원 탈퇴").setMessage(easy()?"정말 탈퇴할까요?":"정말 탈퇴하시겠습니까?\n등록 농경지와 알림 수신 정보가 삭제되며 되돌릴 수 없습니다.").setNegativeButton("취소",null).setPositiveButton("탈퇴하기",(d,which)->withdrawAccount()).create();dialog.setOnShowListener(v->{if(easy()){TextView message=dialog.findViewById(android.R.id.message);if(message!=null)message.setTextSize(24);dialog.getButton(AlertDialog.BUTTON_NEGATIVE).setTextSize(20);dialog.getButton(AlertDialog.BUTTON_POSITIVE).setTextSize(20);}});dialog.show();}
    private void withdrawAccount(){String currentToken=token();new Thread(()->{try{Api.delete("/api/mobile/me",currentToken);runOnUiThread(()->{prefs().edit().clear().apply();pendingName=null;pendingPhone=null;selectedDistrict=null;selectedLocality=null;stopService(new Intent(this,NotificationRelayService.class));toast("회원 탈퇴가 완료되었습니다.");showWelcome();});}catch(Exception e){runOnUiThread(()->toast("회원 탈퇴 실패: "+e.getMessage()));}}).start();}
    private void hideSystemBars(){View decor=getWindow().getDecorView();if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=decor.getWindowInsetsController();if(c!=null){c.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}else decor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}
    private void showSystemBars(){View decor=getWindow().getDecorView();getWindow().setStatusBarColor(Color.rgb(235,247,240));getWindow().setNavigationBarColor(Color.rgb(239,245,250));if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=decor.getWindowInsetsController();if(c!=null){c.show(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());c.setSystemBarsAppearance(WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);}}else decor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);}
    private void startRelay(){Intent i=new Intent(this,NotificationRelayService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
    private android.content.SharedPreferences prefs(){return getSharedPreferences("session",MODE_PRIVATE);}private String token(){return prefs().getString("token","");}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density);}
}
