package kr.co.farmerflood.mobile;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.ActivityInfo;import android.content.pm.PackageManager;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.view.*;import android.webkit.*;import android.widget.*;import org.json.*;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity {
    private enum Screen {WELCOME, ROLE, IDENTITY, LOCATION, FARM_MAP, HOME, VIDEO}
    private LinearLayout root;private EditText name,phone;private Spinner district,locality;private JSONObject regionData;private String pendingName,pendingPhone,selectedDistrict,selectedLocality;private boolean videoMode,farmMapMode;private Screen screen=Screen.WELCOME;private final Handler guardianHandler=new Handler(Looper.getMainLooper());private Runnable guardianPoll;private TextView guardianStatusView;private final BroadcastReceiver newAlertReceiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(screen==Screen.HOME&&guardianStatusView!=null)startGuardianStatus(guardianStatusView);}};
    @Override public void onCreate(Bundle b){super.onCreate(b);IntentFilter filter=new IntentFilter("kr.co.farmerflood.mobile.NEW_ALERT");if(Build.VERSION.SDK_INT>=33)registerReceiver(newAlertReceiver,filter,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(newAlertReceiver,filter);if(Build.VERSION.SDK_INT>=33){getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,this::handleBack);if(checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},100);}String video=getIntent().getStringExtra("mediaUrl");if(video!=null){showVideo(video);return;}String token=prefs().getString("token",null);if(token==null||token.isBlank())showWelcome();else showHome();}
    @Override protected void onDestroy(){stopGuardianPoll();try{unregisterReceiver(newAlertReceiver);}catch(Exception ignored){}super.onDestroy();}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);String video=i.getStringExtra("mediaUrl");if(video!=null)showVideo(video);}
    @Override public void onBackPressed(){handleBack();}
    private void handleBack(){if(screen==Screen.VIDEO){exitVideo();return;}if(screen==Screen.FARM_MAP){showLocation();return;}if(screen==Screen.ROLE||screen==Screen.IDENTITY||screen==Screen.LOCATION){pendingName=null;pendingPhone=null;showWelcome();return;}if(screen==Screen.HOME){moveTaskToBack(true);return;}finish();}
    private void base(){stopGuardianPoll();videoMode=false;farmMapMode=false;setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_VERTICAL);root.setPadding(dp(24),dp(32),dp(24),dp(32));GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(235,247,240),Color.rgb(248,246,235),Color.rgb(239,245,250)});root.setBackground(bg);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.addView(root,new ScrollView.LayoutParams(-1,-1));setContentView(scroll);scroll.post(this::showSystemBars);}
    private TextView text(String value,int size,boolean bold){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(Color.rgb(24,49,39));if(bold)v.setTypeface(null,1);v.setPadding(0,dp(6),0,dp(8));root.addView(v);return v;}
    private EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(17);e.setPadding(dp(18),0,dp(18),0);e.setBackground(round(Color.WHITE,16,Color.rgb(215,227,220)));e.setElevation(dp(1));root.addView(e,new LinearLayout.LayoutParams(-1,dp(60)));space();return e;}
    private Button button(String label){Button b=new Button(this);b.setText(label);b.setTextColor(Color.WHITE);b.setTextSize(16);b.setAllCaps(false);b.setBackground(round(Color.rgb(23,107,67),16,Color.TRANSPARENT));b.setElevation(dp(3));root.addView(b,new LinearLayout.LayoutParams(-1,dp(56)));space();return b;}
    private TextView badge(String value,int fg,int bg){TextView v=new TextView(this);v.setText(value);v.setTextColor(fg);v.setTextSize(13);v.setTypeface(null,1);v.setGravity(Gravity.CENTER);v.setPadding(dp(12),dp(8),dp(12),dp(8));v.setBackground(round(bg,20,Color.TRANSPARENT));return v;}
    private LinearLayout infoRow(String label,String value,int tint){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(16),dp(12),dp(16),dp(12));TextView l=new TextView(this);l.setText(label);l.setTextSize(12);l.setTypeface(null,1);l.setTextColor(tint);TextView v=new TextView(this);v.setText(value);v.setTextSize(16);v.setTypeface(null,1);v.setTextColor(Color.rgb(25,46,40));v.setPadding(0,dp(3),0,0);row.addView(l);row.addView(v);return row;}
    private GradientDrawable round(int color,int radius,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(stroke!=Color.TRANSPARENT)d.setStroke(dp(1),stroke);return d;}
    private void space(){Space s=new Space(this);root.addView(s,new LinearLayout.LayoutParams(1,dp(12)));}
    private void showWelcome(){screen=Screen.WELCOME;base();TextView mark=text("FARM SAFE · CHUNGBUK",13,true);mark.setTextColor(Color.rgb(24,115,79));text("우리 가족을 위한\n한발 빠른 홍수 경고",34,true);TextView intro=text("농업인과 보호자가 함께 농경지 주변의\n위험을 확인하고 경고 영상을 받아보세요.",16,false);intro.setTextColor(Color.rgb(71,91,83));LinearLayout features=new LinearLayout(this);features.setOrientation(LinearLayout.HORIZONTAL);features.setGravity(Gravity.CENTER);features.setPadding(0,dp(12),0,dp(20));features.addView(badge("실시간 수위",Color.rgb(18,96,69),Color.rgb(218,241,230)));features.addView(badge("24시간 강우",Color.rgb(37,91,145),Color.rgb(222,237,250)));features.addView(badge("가족 공유",Color.rgb(140,82,18),Color.rgb(250,234,207)));root.addView(features);Button signup=button("처음 가입하기");Button login=button("기존 회원 로그인");login.setTextColor(Color.rgb(23,107,67));login.setBackground(round(Color.argb(235,255,255,255),16,Color.rgb(174,207,190)));signup.setOnClickListener(v->showRoleChoice(false));login.setOnClickListener(v->showRoleChoice(true));}
    private void showRoleChoice(boolean login){screen=Screen.ROLE;base();text(login?"로그인 유형":"가입 유형",13,true).setTextColor(Color.rgb(23,107,67));text("어떤 역할로\n이용하시나요?",30,true);text("본인에게 맞는 유형을 선택해주세요.",16,false);Button farmer=button("농업인 "+(login?"로그인":"가입"));Button guardian=button("보호자 "+(login?"로그인":"가입"));guardian.setTextColor(Color.rgb(38,91,145));guardian.setBackground(round(Color.rgb(229,240,250),16,Color.rgb(174,203,226)));farmer.setOnClickListener(v->showIdentity(login));guardian.setOnClickListener(v->showGuardianAuth(login));}
    private void showGuardianAuth(boolean login){screen=Screen.IDENTITY;base();text(login?"보호자 로그인":"보호자 가입",13,true).setTextColor(Color.rgb(38,91,145));text("보호자와 농업인\n정보를 입력하세요",29,true);text("연결할 농업인은 먼저 농업인 가입이 완료되어 있어야 합니다.",15,false);EditText guardianName=input("보호자 이름");EditText farmerName=input("가입한 농업인 이름");EditText farmerPhone=input("가입한 농업인 전화번호");farmerPhone.setInputType(3);Button submit=button(login?"보호자로 로그인":"보호자 가입 완료");submit.setBackground(round(Color.rgb(38,101,151),16,Color.TRANSPARENT));submit.setOnClickListener(v->{String g=guardianName.getText().toString().trim(),f=farmerName.getText().toString().trim(),p=farmerPhone.getText().toString().trim();if(g.isEmpty()||f.isEmpty()||p.length()<10){toast("보호자와 농업인 정보를 확인해주세요.");return;}JSONObject body=new JSONObject();try{body.put("guardianName",g).put("farmerName",f).put("farmerPhone",p);}catch(Exception ignored){}authenticateGuardian(login?"/api/mobile/auth/guardian/login":"/api/mobile/auth/guardian/signup",body,g);});}
    private void showIdentity(boolean login){screen=Screen.IDENTITY;base();TextView step=text(login?"다시 만나 반가워요":"회원가입 · 1/3",13,true);step.setTextColor(Color.rgb(23,107,67));text(login?"기존 회원 로그인":"기본 정보를\n알려주세요",30,true);text(login?"가입할 때 사용한 정보를 입력해주세요.":"재난 알림을 정확히 전달하는 데 사용합니다.",16,false);name=input("이름");phone=input("전화번호 (예: 01012345678)");phone.setInputType(3);Button next=button(login?"안전 현황 확인하기":"농경지 위치 등록하기");next.setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()||phone.getText().toString().trim().length()<10){toast("이름과 전화번호를 확인해주세요.");return;}if(login)authenticate("/api/mobile/auth/login",null);else{pendingName=name.getText().toString().trim();pendingPhone=phone.getText().toString().trim();showLocation();}});}
    private void showLocation(){screen=Screen.LOCATION;base();text("농경지 등록 · 2/3",13,true).setTextColor(Color.rgb(38,102,151));text("농경지가 있는\n지역을 선택하세요",28,true);text("선택한 지역의 공식 팜맵으로 이동합니다.",15,false);text("도/광역시",13,true);Spinner province=new Spinner(this);province.setPadding(dp(8),0,dp(8),0);province.setBackground(round(Color.WHITE,14,Color.rgb(205,222,213)));province.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,List.of("충청북도")));root.addView(province,new LinearLayout.LayoutParams(-1,dp(56)));space();text("시/군",13,true);district=new Spinner(this);district.setPadding(dp(8),0,dp(8),0);district.setBackground(round(Color.WHITE,14,Color.rgb(205,222,213)));root.addView(district,new LinearLayout.LayoutParams(-1,dp(56)));space();text("읍/면/동",13,true);locality=new Spinner(this);locality.setPadding(dp(8),0,dp(8),0);locality.setBackground(round(Color.WHITE,14,Color.rgb(205,222,213)));root.addView(locality,new LinearLayout.LayoutParams(-1,dp(56)));space();Button submit=button("지도에서 내 농경지 찾기  →");submit.setEnabled(false);submit.setOnClickListener(v->showFarmMap());new Thread(()->{try{regionData=Api.get("/api/mobile/regions",null).getJSONObject("districts");List<String> districts=new ArrayList<>();regionData.keys().forEachRemaining(districts::add);runOnUiThread(()->{district.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,districts));district.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){loadLocalities(districts.get(pos));}});submit.setEnabled(true);});}catch(Exception e){runOnUiThread(()->toast("행정구역을 불러오지 못했습니다: "+e.getMessage()));}}).start();}
    private void loadLocalities(String d){try{JSONArray a=regionData.getJSONArray(d);List<String> values=new ArrayList<>();for(int i=0;i<a.length();i++)values.add(a.getString(i));locality.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,values));}catch(Exception e){toast(e.getMessage());}}
    private void showFarmMap(){if(district.getSelectedItem()==null||locality.getSelectedItem()==null)return;screen=Screen.FARM_MAP;selectedDistrict=district.getSelectedItem().toString();selectedLocality=locality.getSelectedItem().toString();farmMapMode=true;LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(Color.rgb(244,248,246));Button back=new Button(this);back.setText("←  지역 다시 선택");back.setTextColor(Color.rgb(23,107,67));back.setTextSize(15);back.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);back.setBackgroundColor(Color.WHITE);back.setOnClickListener(v->showLocation());page.addView(back,new LinearLayout.LayoutParams(-1,dp(54)));WebView web=new WebView(this);web.setBackgroundColor(Color.rgb(233,241,236));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);web.addJavascriptInterface(new Object(){@JavascriptInterface public void onParcelSelected(String json){runOnUiThread(()->{try{signup(new JSONObject(json).getString("id"));}catch(Exception e){toast("농경지 선택 정보를 확인할 수 없습니다.");}});}},"AndroidFarmMap");page.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(page);String url=BuildConfig.API_BASE_URL+"/mobile/farm-map?district="+URLEncoder.encode(selectedDistrict,StandardCharsets.UTF_8)+"&locality="+URLEncoder.encode(selectedLocality,StandardCharsets.UTF_8);web.loadUrl(url);}
    private void signup(String parcelId){JSONObject extra=new JSONObject();try{extra.put("district",selectedDistrict).put("locality",selectedLocality).put("parcelId",parcelId);}catch(Exception ignored){}authenticate("/api/mobile/auth/signup",extra);}
    private void authenticate(String path,JSONObject extra){final String n=pendingName==null?name.getText().toString().trim():pendingName,p=pendingPhone==null?phone.getText().toString().trim():pendingPhone;new Thread(()->{try{JSONObject body=extra==null?new JSONObject():extra;body.put("name",n).put("phone",p);JSONObject result=Api.post(path,body,null);saveSession(result,n);runOnUiThread(this::showHome);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}).start();}
    private void authenticateGuardian(String path,JSONObject body,String guardianName){new Thread(()->{try{JSONObject result=Api.post(path,body,null);saveSession(result,guardianName);runOnUiThread(this::showHome);}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}).start();}
    private void saveSession(JSONObject result,String displayName)throws Exception{JSONObject user=result.optJSONObject("user");String role=user==null?"FARMER":user.optString("role","FARMER");prefs().edit().putString("token",result.getString("token")).putString("name",displayName).putString("role",role).putString("targetFarmerName",result.optString("targetFarmerName","")).remove("lastNotificationId").remove("notificationBaselineInitialized").commit();}
    private void showHome(){screen=Screen.HOME;base();startRelay();
        boolean guardian="GUARDIAN".equals(prefs().getString("role","FARMER"));String target=prefs().getString("targetFarmerName","농업인");LinearLayout header=new LinearLayout(this);header.setOrientation(LinearLayout.VERTICAL);header.setPadding(dp(18),dp(18),dp(18),dp(18));header.setBackground(round(guardian?Color.rgb(42,91,139):Color.rgb(26,105,77),22,Color.TRANSPARENT));header.setElevation(dp(3));TextView greeting=new TextView(this);greeting.setText(prefs().getString("name",guardian?"보호자":"농업인")+"님은 보호자 로그인입니다.");if(!guardian)greeting.setText(prefs().getString("name","농업인")+"님, 안녕하세요");greeting.setTextSize(guardian?22:27);greeting.setTypeface(null,1);greeting.setTextColor(Color.WHITE);TextView message=new TextView(this);message.setText(guardian?target+"님의 농경지 경고 영상 및\n조회 여부를 확인합니다.":"오늘도 농경지 주변의 하천과 비 소식을\n꼼꼼하게 살피고 있어요.");message.setTextSize(15);message.setTextColor(guardian?Color.rgb(221,237,250):Color.rgb(218,241,231));message.setPadding(0,dp(8),0,dp(12));header.addView(greeting);header.addView(message);header.addView(badge(guardian?"●  보호자 안전 연결 중":"●  실시간 안전 감시 중",guardian?Color.rgb(37,82,125):Color.rgb(18,91,67),guardian?Color.rgb(225,239,251):Color.rgb(220,244,231)));root.addView(header,new LinearLayout.LayoutParams(-1,-2));space();
        TextView section=text(guardian?"대상 농경지":"내 농경지",18,true);section.setTextColor(Color.rgb(28,65,53));LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(4),dp(6),dp(4),dp(6));card.setBackground(round(Color.argb(242,255,255,255),20,Color.rgb(218,229,222)));card.setElevation(dp(2));card.addView(infoRow("농경지", "정보를 불러오는 중입니다…",Color.rgb(29,112,79)));root.addView(card,new LinearLayout.LayoutParams(-1,-2));space();
        TextView readStatus=null;if(guardian){readStatus=new TextView(this);readStatus.setText("최근 영상 확인 여부를 조회 중입니다…");readStatus.setTextSize(15);readStatus.setTypeface(null,1);readStatus.setTextColor(Color.rgb(151,43,43));readStatus.setGravity(Gravity.CENTER);readStatus.setPadding(dp(16),dp(15),dp(16),dp(15));readStatus.setBackground(round(Color.rgb(251,231,231),16,Color.rgb(239,190,190)));root.addView(readStatus,new LinearLayout.LayoutParams(-1,-2));space();guardianStatusView=readStatus;startGuardianStatus(readStatus);}else{guardianStatusView=null;LinearLayout notice=new LinearLayout(this);notice.setOrientation(LinearLayout.VERTICAL);notice.setPadding(dp(18),dp(16),dp(18),dp(16));notice.setBackground(round(Color.rgb(231,241,250),18,Color.TRANSPARENT));TextView noticeTitle=new TextView(this);noticeTitle.setText("최근 경고 영상");noticeTitle.setTextSize(15);noticeTitle.setTypeface(null,1);noticeTitle.setTextColor(Color.rgb(38,86,128));TextView noticeBody=new TextView(this);noticeBody.setText("가장 최근에 제작된 홍수 경고 영상을 다시 볼 수 있습니다.");noticeBody.setTextSize(14);noticeBody.setTextColor(Color.rgb(65,82,96));noticeBody.setPadding(0,dp(5),0,0);notice.addView(noticeTitle);notice.addView(noticeBody);root.addView(notice);space();}Button refresh=button("경고 영상 재확인");refresh.setBackground(round(Color.rgb(37,101,151),16,Color.TRANSPARENT));refresh.setOnClickListener(v->loadLatest());
        Space separation=new Space(this);root.addView(separation,new LinearLayout.LayoutParams(1,dp(28)));LinearLayout accountActions=new LinearLayout(this);accountActions.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);Button logout=new Button(this);logout.setText("로그아웃");logout.setAllCaps(false);logout.setTextSize(14);logout.setTextColor(Color.rgb(71,85,80));logout.setBackground(round(Color.argb(220,255,255,255),14,Color.rgb(205,216,210)));LinearLayout.LayoutParams logoutParams=new LinearLayout.LayoutParams(dp(138),dp(48));logoutParams.setMargins(0,0,dp(12),0);accountActions.addView(logout,logoutParams);Button withdraw=new Button(this);withdraw.setText("회원 탈퇴");withdraw.setAllCaps(false);withdraw.setTextSize(12);withdraw.setTextColor(Color.rgb(169,54,54));withdraw.setBackground(round(Color.rgb(250,238,238),14,Color.TRANSPARENT));accountActions.addView(withdraw,new LinearLayout.LayoutParams(dp(112),dp(44)));root.addView(accountActions);logout.setOnClickListener(v->{prefs().edit().clear().commit();pendingName=null;pendingPhone=null;stopService(new Intent(this,NotificationRelayService.class));showWelcome();});withdraw.setOnClickListener(v->confirmWithdrawal());
        new Thread(()->{try{JSONObject me=Api.get("/api/mobile/me",token());JSONObject f=me.optJSONObject("farmland");runOnUiThread(()->{card.removeAllViews();if(f==null){card.addView(infoRow("농경지","등록된 농경지가 없습니다.",Color.rgb(29,112,79)));return;}card.addView(infoRow("농경지",f.optString("name","내 농경지"),Color.rgb(29,112,79)));card.addView(infoRow("위치",f.optString("address","위치 정보 없음"),Color.rgb(38,101,151)));card.addView(infoRow("현재 상태","인근 하천 안전 감시 중",Color.rgb(151,91,28)));});}catch(Exception e){runOnUiThread(()->toast(e.getMessage()));}}).start();}
    private void loadLatest(){new Thread(()->{try{JSONArray list=Api.getArray("/api/mobile/notifications",token());if(list.length()==0){runOnUiThread(()->toast("현재는 홍수 위험이 발생하지 않았습니다."));return;}JSONObject latest=list.getJSONObject(0);String url=latest.optString("mediaUrl","");if(url.isBlank()){runOnUiThread(()->toast("현재는 홍수 위험이 발생하지 않았습니다."));return;}runOnUiThread(()->showVideo(url,latest.optString("id",null)));}catch(Exception e){runOnUiThread(()->toast("현재는 홍수 위험이 발생하지 않았습니다."));}}).start();}
    private void startGuardianStatus(TextView view){stopGuardianPoll();guardianPoll=new Runnable(){@Override public void run(){if(screen!=Screen.HOME||view!=guardianStatusView)return;new Thread(()->{try{JSONArray list=Api.getArray("/api/mobile/notifications",token());if(list.length()==0){runOnUiThread(()->{if(view!=guardianStatusView)return;view.setText("현재 확인할 경고 영상이 없습니다.");view.setTextColor(Color.rgb(108,91,64));view.setBackground(round(Color.rgb(248,240,219),16,Color.rgb(232,214,170)));guardianHandler.postDelayed(this,5000);});return;}JSONObject latest=list.getJSONObject(0);boolean read=!latest.isNull("readAt")&&!latest.optString("readAt","").isBlank();runOnUiThread(()->{if(view!=guardianStatusView)return;if(read){view.setText("농업인이 최신 경고 영상을 확인했습니다.");view.setTextColor(Color.rgb(35,83,130));view.setBackground(round(Color.rgb(225,239,251),16,Color.rgb(169,204,231)));stopGuardianPoll();}else{view.setText("농업인이 아직 최신 경고 영상을 확인하지 않았습니다.");view.setTextColor(Color.rgb(151,43,43));view.setBackground(round(Color.rgb(251,231,231),16,Color.rgb(239,190,190)));guardianHandler.postDelayed(this,5000);}});}catch(Exception e){runOnUiThread(()->{if(view==guardianStatusView)guardianHandler.postDelayed(this,5000);});}}).start();}};guardianHandler.post(guardianPoll);}
    private void stopGuardianPoll(){if(guardianPoll!=null)guardianHandler.removeCallbacks(guardianPoll);guardianPoll=null;}
    private void showVideo(String path){showVideo(path,getIntent().getStringExtra("notificationId"));}
    private void showVideo(String path,String notificationId){
        screen=Screen.VIDEO;videoMode=true;
        if(notificationId!=null&&!"GUARDIAN".equals(prefs().getString("role","FARMER")))new Thread(()->{try{Api.post("/api/mobile/notifications/"+notificationId+"/read",null,token());}catch(Exception ignored){}}).start();
        // 가로 전환으로 Activity가 재생성되어도 홈 버튼/알림에서 받은 영상 주소를 유지한다.
        getIntent().putExtra("mediaUrl",path);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);
        FrameLayout stage=new FrameLayout(this);stage.setBackgroundColor(Color.BLACK);
        VideoView video=new VideoView(this);FrameLayout.LayoutParams videoParams=new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER);stage.addView(video,videoParams);
        Button close=new Button(this);close.setText("끄기  ✕");close.setAllCaps(false);close.setTextColor(Color.WHITE);close.setTextSize(15);close.setTypeface(null,1);close.setPadding(dp(14),0,dp(14),0);close.setBackground(round(Color.rgb(190,45,45),18,Color.TRANSPARENT));close.setElevation(dp(12));close.setOnClickListener(v->exitVideo());
        FrameLayout.LayoutParams closeParams=new FrameLayout.LayoutParams(dp(104),dp(48),Gravity.END|Gravity.TOP);
        closeParams.setMargins(dp(16),dp(16),dp(20),dp(16));stage.addView(close,closeParams);close.bringToFront();
        setContentView(stage);stage.post(this::hideSystemBars);video.setVideoURI(Uri.parse(BuildConfig.API_BASE_URL+path));MediaController controls=new MediaController(this){@Override public boolean dispatchKeyEvent(KeyEvent event){if(event.getKeyCode()==KeyEvent.KEYCODE_BACK){if(event.getAction()==KeyEvent.ACTION_UP)exitVideo();return true;}return super.dispatchKeyEvent(event);}};controls.setAnchorView(video);video.setMediaController(controls);video.setOnPreparedListener(mp->{mp.setLooping(false);int vw=mp.getVideoWidth(),vh=mp.getVideoHeight(),sw=stage.getWidth(),sh=stage.getHeight();if(vw>0&&vh>0&&sw>0&&sh>0){float scale=Math.min((float)sw/vw,(float)sh/vh);FrameLayout.LayoutParams centered=new FrameLayout.LayoutParams(Math.round(vw*scale),Math.round(vh*scale),Gravity.CENTER);video.setLayoutParams(centered);}video.start();close.bringToFront();});video.setOnErrorListener((mp,what,extra)->{toast("영상을 재생할 수 없습니다.");return true;});
    }
    private void exitVideo(){videoMode=false;getIntent().removeExtra("mediaUrl");getIntent().removeExtra("notificationId");showSystemBars();setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);showHome();}
    private void confirmWithdrawal(){new AlertDialog.Builder(this).setTitle("회원 탈퇴").setMessage("정말 탈퇴하시겠습니까?\n등록 농경지와 알림 수신 정보가 삭제되며 되돌릴 수 없습니다.").setNegativeButton("취소",null).setPositiveButton("탈퇴하기",(dialog,which)->withdrawAccount()).show();}
    private void withdrawAccount(){String currentToken=token();new Thread(()->{try{Api.delete("/api/mobile/me",currentToken);runOnUiThread(()->{prefs().edit().clear().apply();stopService(new Intent(this,NotificationRelayService.class));toast("회원 탈퇴가 완료되었습니다.");showWelcome();});}catch(Exception e){runOnUiThread(()->toast("회원 탈퇴 실패: "+e.getMessage()));}}).start();}
    private void hideSystemBars(){View decor=getWindow().getDecorView();if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=decor.getWindowInsetsController();if(c!=null){c.hide(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}else decor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}
    private void showSystemBars(){View decor=getWindow().getDecorView();if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=decor.getWindowInsetsController();if(c!=null)c.show(WindowInsets.Type.statusBars()|WindowInsets.Type.navigationBars());}else decor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_VISIBLE);}
    private void startRelay(){Intent i=new Intent(this,NotificationRelayService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);}
    private android.content.SharedPreferences prefs(){return getSharedPreferences("session",MODE_PRIVATE);}private String token(){return prefs().getString("token","");}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density);}
}
